name: Publish on Deno Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup Deno environment
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build site
        run: |
          cd static
          deno task build
          cp deno.json _site/
          cp import_map.json _site/
          cp serve.ts _site/
          cp redirects.json _site/

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: letrag
          import-map: import_map.json
          entrypoint: serve.ts
          root: static/_site